swagger: '2.0'
info:
  description: Products REST API for Xero
  version: '1.0'
  title: Products REST API for Xero
paths:
  /products/093f3541-cb06-45c2-b87e-8c104f5de9fc/options/e9c0b9b5-bc8c-4c4a-869f-23cc39e245b3:
    get:
      produces:
        - application/json
      parameters:
        - name: k
          in: header
          description: >-
            Generated header parameter. Example value
            ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM'
          required: true
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM
      responses:
        '200':
          description: Finds the specified product option for the specified product.
          schema:
            $ref: '#/definitions/Model7'
      security:
        - Secured: []
    put:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: k
          in: header
          description: >-
            Generated header parameter. Example value
            ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM'
          required: true
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Model1'
          x-examples:
            application/json: |-
              {
                  "name": "Candy updated product option",
                  "description": "Candy updated product option description"
              }
      responses:
        '200':
          description: Updates the specified product option.
          schema:
            $ref: '#/definitions/Model6'
      security:
        - Secured: []
    delete:
      consumes:
        - application/json
      parameters:
        - name: k
          in: header
          description: >-
            Generated header parameter. Example value
            ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM'
          required: true
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM
      responses:
        '204':
          description: Deletes the specified product option.
          schema:
            type: string
      security:
        - Secured: []
  /products/093f3541-cb06-45c2-b87e-8c104f5de9fc/options:
    get:
      produces:
        - application/json
      parameters:
        - name: k
          in: header
          description: >-
            Generated header parameter. Example value
            ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM'
          required: true
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM
      responses:
        '200':
          description: Finds all options for a specified product.
          schema:
            $ref: '#/definitions/Model8'
      security:
        - Secured: []
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: k
          in: header
          description: >-
            Generated header parameter. Example value
            ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM'
          required: true
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Model4'
          x-examples:
            application/json: |-
              {
                  "name": "Candy product option",
                  "description": "Candy product option description"
              }
      responses:
        '201':
          description: Adds a new product option to the specified product.
          schema:
            $ref: '#/definitions/Model9'
      security:
        - Secured: []
  /products/dff20c10-ab57-47e6-a36c-cb5ce3a82a9b:
    delete:
      consumes:
        - application/json
      parameters:
        - name: k
          in: header
          description: >-
            Generated header parameter. Example value
            ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM'
          required: true
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM
      responses:
        '204':
          description: Deletes a product and its options.
          schema:
            type: string
      security:
        - Secured: []
  /products/093f3541-cb06-45c2-b87e-8c104f5de9fc:
    put:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: k
          in: header
          description: >-
            Generated header parameter. Example value
            ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM'
          required: true
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Model5'
          x-examples:
            application/json: |-
              {
                  "name": "Candy updated name",
                  "description": "Candy updated description",
                  "price": 34.56,
                  "deliveryPrice": 2.34
              }
      responses:
        '200':
          description: Updates a product
          schema:
            $ref: '#/definitions/Model10'
      security:
        - Secured: []
  /products:
    get:
      produces:
        - application/json
      parameters:
        - name: name
          in: query
          required: false
          type: string
          x-example: phone
        - name: limit
          in: query
          required: false
          type: string
          x-example: '5'
        - name: page
          in: query
          required: false
          type: string
          x-example: '1'
        - name: k
          in: header
          description: >-
            Generated header parameter. Example value
            ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM'
          required: true
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM
      responses:
        '200':
          description: Gets all products / Finds all products matching the specified name
          schema:
            $ref: '#/definitions/Model16'
      security:
        - Secured: []
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: k
          in: header
          description: >-
            Generated header parameter. Example value
            ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM'
          required: true
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Model0'
          x-examples:
            application/json: |-
              {
                  "name": "Candy",
                  "description": "Candy description",
                  "price": 12.34,
                  "deliveryPrice": 1.23
              }
      responses:
        '201':
          description: Creates a new product
          schema:
            $ref: '#/definitions/Model11'
      security:
        - Secured: []
  /products/e14bbb15-47e1-41da-96b2-0e141f94da93:
    get:
      produces:
        - application/json
      parameters:
        - name: k
          in: header
          description: >-
            Generated header parameter. Example value
            ='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM'
          required: true
          type: string
          x-example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3ZTE0OTlkLTNmNWYtNGMxNC04ZjY1LTBjZjBkNTJhMWYzYSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obi5kb2VAZW1haWwuY29tIn0.SJUucdpb_06OTJdxSstmBrACFOubju7mXcaJyGZmVtM
      responses:
        '200':
          description: Gets the product that matches the specified ID
          schema:
            $ref: '#/definitions/Model12'
      security:
        - Secured: []
securityDefinitions:
  Secured:
    type: basic
definitions:
  Model0:
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: double
      deliveryPrice:
        type: number
        format: double
  Model1:
    properties:
      name:
        type: string
      description:
        type: string
  Model4:
    properties:
      name:
        type: string
      description:
        type: string
  Model5:
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: double
      deliveryPrice:
        type: number
        format: double
  Data:
    properties:
      name:
        type: string
      description:
        type: string
      product:
        type: string
      id:
        type: string
  Model6:
    properties:
      success:
        type: boolean
      data:
        $ref: '#/definitions/Data'
  Product:
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: double
      deliveryPrice:
        type: number
        format: double
      productOptions:
        type: array
        items:
          type: string
      id:
        type: string
  Model7_Data:
    properties:
      name:
        type: string
      description:
        type: string
      product:
        $ref: '#/definitions/Product'
      id:
        type: string
  Model7:
    properties:
      success:
        type: boolean
      data:
        $ref: '#/definitions/Model7_Data'
  Items:
    properties:
      name:
        type: string
      description:
        type: string
      product:
        type: string
      id:
        type: string
  Model8_Data:
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/Items'
  Model8:
    properties:
      success:
        type: boolean
      data:
        $ref: '#/definitions/Model8_Data'
  Model9_Data:
    properties:
      name:
        type: string
      description:
        type: string
      product:
        type: string
      id:
        type: string
  Model9:
    properties:
      success:
        type: boolean
      data:
        $ref: '#/definitions/Model9_Data'
  Model10_Data:
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: double
      deliveryPrice:
        type: number
        format: double
      productOptions:
        type: array
      id:
        type: string
  Model10:
    properties:
      success:
        type: boolean
      data:
        $ref: '#/definitions/Model10_Data'
  Model11_Data:
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: double
      deliveryPrice:
        type: number
        format: double
      productOptions:
        type: array
      id:
        type: string
  Model11:
    properties:
      success:
        type: boolean
      data:
        $ref: '#/definitions/Model11_Data'
  Model12_Data:
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: double
      deliveryPrice:
        type: number
        format: double
      productOptions:
        type: array
      id:
        type: string
  Model12:
    properties:
      success:
        type: boolean
      data:
        $ref: '#/definitions/Model12_Data'
  Model16_Data_Items:
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: double
      deliveryPrice:
        type: number
        format: double
      productOptions:
        type: array
      id:
        type: string
  Model16_Data:
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/Model16_Data_Items'
  Model16:
    properties:
      success:
        type: boolean
      data:
        $ref: '#/definitions/Model16_Data'